IFComp/lib/IFComp/Controller/Play.pm
IFComp/lib/IFComp/Schema/Result/Entry.pm
README.md

This patch makes it so at the time the platform is generated (by analyzing the uploaded files), it also picks one file as the play_file. For the web platforms, this file is linked to by play online (the play file doesn't get used for the non-web platforms, but you can imagine down the line the site could generate a custom parchment build based on the file or something).

Issue 63: Create a play_file attribute for entries to to show which file to link to from play online

---

IFComp/lib/IFComp/Controller/Play.pm

This is hard for me to test locally for obvious reasons, but I was able to do some sample code that also showed the issue, so I think this is the right fix. Basically, I think req->body_data has already been converted from bytes to a string, so decode_json is the wrong function; from_json is what you use for strings.

Issue 64: json is already a string, not bytes, so use from_json instead

---

IFComp/cpanfile
IFComp/lib/IFComp/Schema/Result/VoteFromQualifiedJudgeBallot.pm
IFComp/script/update_current_rating_tallies

This adds the following:
* A new 'virtual' resultset, VoteFromQualifiedJudgeBallot, that provides a (read-only) view to the Vote table with the following restrictions:
* Counts only ballots containing at least five ratings
* Disregards ballots from the given competition's entrants
* A script, intended to be run as a crontask, that updates all the derived fields for the current comp's qualified entries.

Ballot crontasks

---

.gitignore
.tidyallrc
IFComp/.perltidyrc
IFComp/cpanfile
IFComp/xt/tidyall.t

This adds Perl::Tidy and Code::TidyAll to the prereqs, along with configs for each.
Perl::Tidy is a module and CLI tool for parsing and prettifying perl code. Code::TidyAll is a module and CLI tool for running various formatters and validators. It's only set up to run Perl::Tidy here, but there are many other options we can add later, eg Perl::Critic or PodChecker.
perltidy will format code according to a set of rules, in IFComp/.perltidyrc. This is the same config I've been using for years, and is generally the same as the style recommended by Perl Best Practices.
This PR is less about prescribing this formatting style in particular, and more about getting the tooling in place so that we can start to establish and encourage some set of coding standards. This config seems as good a place …

Add perltidy and tidyall config, prereqs, and test.

---

IFComp/lib/IFComp/Controller/Play.pm

Filenames with commas cause Chrome to interpret the header as two
headers. That is,
Content-Disposition: attachment; filename=SCREW YOU, BEAR DAD.html
is interpreted as
Content-Disposition: attachment; filename=SCREW YOU
Content-Disposition: BEAR DAD.html
Quoting the filename should fix this issue.

Quote attachment name in Content-Disposition header.

---

IFComp/lib/IFComp/Form/Entry.pm
IFComp/lib/IFComp/Schema/Result/Entry.pm
IFComp/root/src/_current_entry_row.tt
IFComp/root/src/entry/_form.tt

This adds support for a content warning field to the database schema, the entry form, and the ballot. It is a free-text field, which authors can use however they wish (or not at all).
For the sake of flexibility, the IFComp committee decided to add this as a new field, rather than continue to recommend that authors include content warnings in their entries' blurb text. This implements that.
New text on the entry form fibs about judges' ability to hide content warnings. We'll return and add that feature prior to the stat of the 2017 judging period.
SQL:
`alter table entry add column warning text;`

Adding support for a content warning field

---

IFComp/cpanfile
IFComp/lib/IFComp/Form/Entry.pm
IFComp/lib/IFComp/Schema/Result/Entry.pm
IFComp/root/src/_current_entry_row.tt
IFComp/root/src/entry/_form.tt

Adding support for a controlled-vocabulary estimated-playtime field to the entry form, and to entries' ballot display.
The form's options (15 minutes or less, 30 minutes, et cetera) are based on discussion of the IFComp committee, and are subject to tester feedback.

Playtime field

---

.gitignore
IFComp/root/src/_colossal_fund.tt
IFComp/root/src/welcome.tt2

Adds a colossal-fund widget to front page, and (since it's its own template) it's theoretically re-applicable elsewhere as well.
Expects a data file at $APP_HOME/root/lib/config/colossal. (If it's not there, it displays an error div instead of the widget.) The file format is Template Toolkit's native format for data files, because I didn't wanna either add to the controller just to read a YAML file, or repair the apparently broken TT-YAML plugin.
Example data file content:
```
goal_dollars : current_dollars : minimum_prize : maximum_prize : estimated_entries
6000 : 1200 : 10 : 123 : 60
```

Colossal fund progress-bar widget

---

IFComp/cpanfile
IFComp/lib/IFComp/Schema.pm
IFComp/lib/IFComp/Schema/Result/AuthToken.pm
IFComp/lib/IFComp/Schema/Result/Comp.pm
IFComp/lib/IFComp/Schema/Result/Entry.pm
IFComp/lib/IFComp/Schema/Result/EntryUpdate.pm
IFComp/lib/IFComp/Schema/Result/FederatedSite.pm
IFComp/lib/IFComp/Schema/Result/Prize.pm
IFComp/lib/IFComp/Schema/Result/Role.pm
IFComp/lib/IFComp/Schema/Result/Session.pm
IFComp/lib/IFComp/Schema/Result/Transcript.pm
IFComp/lib/IFComp/Schema/Result/User.pm
IFComp/lib/IFComp/Schema/Result/UserRole.pm
IFComp/lib/IFComp/Schema/Result/Vote.pm
IFComp/script/ifcomp_dump_schema.pl
README.md

Addresses #93.
There are a few pieces here:
* I added DBIx::Class::Schema::Loader to the cpanfile's list of develop requirements.
* I updated the README with a note about running cpanm with the --with-develop flag to get those requirements.
* I added a script - ifcomp_dump_schema.pl - for dumping the schema classes from the db. Most notably, it now inserts markers before and after the generated code so that perltidy won't tidy that code and screw up the checksum.
* I dumped the schema, so all of the result classes now have those perltidy markers.
* One side-effect of dumping the schema was that it stripped two column comments from the User class. Those comments don't get inserted by the `ifcomp_deploy_db.pl` script - only databases copied from the original (I'm guessing) will have those …

Add dbicdump script

---

.travis.yml
IFComp/t/controller_Entry.t

Adds the config for Travis-CI (and Coveralls).
Also fixes one test file - `controller_Entry.t` - to create the needed `t/entries` directory when missing.

Add travis ci config

---

IFComp/root/src/about/prizes.tt

The typo'd `</style>` tag was preventing the menubar from operating correctly on the /about/prizes page.

Fix typo'd closing tag.

---

.travis.yml
IFComp/cpanfile
IFComp/lib/IFComp/Controller/Play.pm
IFComp/lib/IFComp/Schema/Result/Entry.pm
IFComp/t/controller_Play.t
IFComp/t/entry_processing.t
IFComp/t/lib/IFCompTest.pm

This adds transcription-supporting configuration to the IFComp web app's quixe interpreter.
It also adds a new test for transcription, from both Parchment-style and Quixe-style sources. (It just calls the transcription action directly with some canned data, and makes sure that expected database rows have been inserted.)
Meta: This is the last PR I plan to make based on the `quixe` branch, before letting testers take the whole thing for a spin on dev. Once it meets they're approval, I'll push it all to production.

Quixe transcripts

---

IFComp/cpanfile
IFComp/lib/IFComp/ColossalFund.pm
IFComp/lib/IFComp/ColossalFund/Donor.pm
IFComp/lib/IFComp/ColossalFund/Year.pm
IFComp/lib/IFComp/Controller/About.pm
IFComp/lib/IFComp/Controller/Root.pm
IFComp/lib/IFComp/Model/ColossalFund.pm
IFComp/root/src/_colossal_fund.tt
IFComp/root/src/about/colossal_fund.tt
IFComp/t/colossal/contributors/1999.csv
IFComp/t/colossal/contributors/2000.csv
IFComp/t/colossal/current_progress.json
IFComp/t/colossal_fund.t
IFComp/t/model_ColossalFund.t

This adds:
• A new action at /about/colossal/[year] that displays a Colossal Fun donor wall for a particular year (defaults to current year), drawing data from a given CSV file
• A new object class (and Catalyst model interface) representing CF donors (current and historical) and facts about the current year's CF drive, drawing data from a given JSON file. This replaces the Template Toolkit datafile currently in use for this purpose.

Colossal fund

---

IFComp/lib/IFComp/Controller/Admin.pm
IFComp/lib/IFComp/Controller/Admin/Voting.pm
IFComp/lib/IFComp/Controller/Admin/Voting/IP.pm
IFComp/lib/IFComp/Controller/Admin/Voting/User.pm
IFComp/t/admin.t
IFComp/t/lib/IFCompTest.pm

Discovered while working on a new admin-only feature that various admin actions weren't correctly chained into the rest of the application. As a result, some pages that should be restricted to admin views are visible to the public (albeit with non-obvious URLs, and half the time resulting in HTTP 500 responses).
This chains them up better, and also simplifies one role-check to use Catalyst standards. There are no changes made to outward-facing paths.

Repairing chained-path config for admin actions.

---

IFComp/lib/IFComp/Controller/Admin.pm
IFComp/lib/IFComp/Controller/Admin/Feedback.pm
IFComp/root/src/admin/feedback/index.tt
IFComp/root/src/admin/index.tt
IFComp/t/feedback.t
IFComp/t/lib/IFCompTest.pm

New action: /admin/feedback
Displays all collected feedback, ordered by judge.
Locked to the 'curator' role because I didn't feel like introducing a new role for this? May change mind on that later.

Adding admin view of feedback.

---

IFComp/lib/IFComp/Controller/About.pm
IFComp/lib/IFComp/Controller/Admin/Voting/IP.pm
IFComp/lib/IFComp/Controller/Entry.pm
IFComp/lib/IFComp/Form/Entry.pm
IFComp/root/src/entry/update.tt
IFComp/t/controller_Play.t
IFComp/t/feedback.t

This uses the add_form_error() method to pass a token back to the form template as there is no specific field to use to inform the author of their mistake. Some minor language processing is done in order to make the error message more natural in the case where more than one mistake has been made.
[also, ran tidyall]

prevent users from submitting too many entries, fixes #85

---

IFComp/lib/IFComp/Controller/Ballot.pm
IFComp/root/src/ballot/index.tt

* Makes random-shuffle the default game sort-order, in /ballot.
* Always make all the sorting buttons available, and shade in the active one.
* Allow random shuffle to work with SQLite. (Needed to add this because the new random-shuffle default appears a lot in test scripts, and the test environment uses SQLite.)

Random default

---

IFComp/lib/IFComp/Controller/Play.pm

This hack was put into place under duress during the 2016 comp, in order to fix certain Twine games that weren't loading... at the cost of removing UTF-8 encoding from them. Per the comments, I didn't know what an "es6-shim" was, and I still don't.
An author noted this year that the downloaded editions of their game had bad encoding (specifically, em-dash characters turned into garbage). The game does contain the "es6-shim" stuff, and the 2016 hack dutifully messed up their game's character encoding.
When I remove this hack, their game loads correctly, and is correctly encoded.
I propose that we declare the problem to have magically fixed itself in the intervening three years, and just revert the hack entirely.

Removing the poorly understood 'es6-shim' hack from 2016

---

IFComp/lib/IFComp/Controller/Ballot.pm

/ballot and /ballot/vote now pull from different root actions. The latter always alphabetizes the stashed entries; the former does it only if there's a parameter asking for it, and shuffles them otherwise.

Fixes #189

---

IFComp/lib/IFComp/Controller/User.pm
IFComp/lib/IFComp/Form/UserFields.pm
IFComp/lib/IFComp/Schema/Result/User.pm
IFComp/root/src/user/register.tt

Prerequisite SQL to run:
```
alter table user add column paypal char(64);
```
This work adds schema support for the above new column, and adds it to user CRUD forms.
DIdn't add any further tests because it rather doesn't seem worthwhile in this case? It's just another optional user form field like many others.

Add paypal address to user accounts

---

IFComp/root/src/entry/list.tt

Simple change to let authors see their own entries' DB IDs.
This is mainly to help them ask comp organizers about game-specific questions.

Expose entry IDs to their authors, on the entry-management screen.

---

IFComp/root/lib/site/header
IFComp/root/src/about/how_to_enter.tt

Replacing the old "how to enter" page with this much-expanded version, based on everything that's happened since 2014.
This is installed on the staging server, and under review separately there.

New author's handbook.

---

IFComp/lib/IFComp/Schema/Result/Entry.pm
IFComp/t/entry_processing.t

This work reduces the changes that the app makes to its online-play copies of entries' Quixe and Parchment-based websites.
In sum, we dramatically simplify the processing done on these games, allowing them to use the technology they were uploaded with instead of forcing them to use ifcomp.org-hosted copies of software. The earlier "mangling" was necessary in 2014-2015 to enact features regarding transcription and work around Inform bugs, but they haven't been necessary in a long time, and have begun to get in the way of newer work.
* It no longer redirects them to use locally hosted interpreters. Instead, entries use their own, uploaded interpreters.
* It no longer has them use the locally hosted copy of if-recorder.js. Instead, it adds a small <script> block that configures the Quixe or …

Simplify transcription setup

---

IFComp/lib/IFComp/Schema/Result/Comp.pm
IFComp/lib/IFComp/Schema/Result/Role.pm
IFComp/lib/IFComp/Schema/Result/User.pm
IFComp/lib/IFComp/Schema/Result/Vote.pm

While performing work on a different issue, I realized that the schema doesn't match the actual database. In particular, `role.name` is defined in the schema with a size of 8, but the actual data going into it is sometimes larger (_votecounter_).
Sure enough, it has a size of 16 in the db itself.
I downloaded a fresh copy of the database from sword and ran `ifcomp_dump_schema.pl`, and this PR is the result.

Update schema to match production db.

---

IFComp/lib/IFComp/Schema/Result/Entry.pm

As I was investigating our current usage of the 'platform' field, I ran across several chunks of dead/unused code that could be removed.

Remove dead code from Result::Entry

---

IFComp/root/src/_filter_entries.tt
IFComp/root/src/ballot/index.tt

Some platforms have multiple enum values depending on whether they can be played in a browser or not. This fix enhances the filters to support that

Update filter code to handle multi-platform descriptions

---

IFComp/lib/IFComp/Controller/Comp.pm
IFComp/root/src/comp/cover_sheet.tt

allows those with the comp curator role to generate a standalone web page suitable for inclusion in the comp's mega-zipfile

clean forward-port of jmac's cover sheet code

---

IFComp/root/src/about/comp.tt

On the ["about" page](https://ifcomp.org/about/comp), the "Rising Star Award" and "Golden Banana of Discord" headings both use the same anchor `banana`. This PR gives them distinct anchors.
(I haven't set up a dev environment to test this, but how badly can I have got it wrong?)
-----
(off-topic noodling follows; I don't intend for this to derail this trivial PR, can re-raise as an Issue if there's interest in discussing:)
I noticed this in passing when wondering what it would take to properly commemorate Rising Star Award recipients on ifcomp.org.
Up until now, I think they've only been recorded in the ceremony video recordings. (I just created [an IFWiki page](https://www.ifwiki.org/Rising_Star_Award) and added a division to the …

Fix anchor for "Rising Star Award" section

---

IFComp/root/src/about/comp.tt

This may seem trivial but it's related to a question at https://intfiction.org/t/authors-judging/64552/4 of conflicting information.
Edit or reject as you wish. While I remember authors were allowed to judge in 2021, newer ones might not & it'd be great to see as many as possible feel confident they can cast votes!

update line to note authors are no longer excluded from voting

---

.github/workflows/Test.yml
README.md

We were getting warnings in the github actions results saying that the v2 versions of checkout & cache were on older versions of node and were being deprecated. This brings us up to date.
I also took the opportunity to remove the old link to the TravisCI results from the readme

update actions to node20 and clean up readme

---

IFComp-Dev/docker-app/Dockerfile

Docker can't directly run `docker_start.sh` from a mounted Windows directory because Windows lacks executable file permissions. This fixes that issue, which caused the app to crash on startup.

Make app dockerfile work on Windows

---

IFComp/root/src/entry/_form.tt

Fixes #397, which broke the script that shows warnings during entry registration. The script now has its intended effect, namely:
- If an author selects the option "_Yes, this entry has already had a prior public release, or I plan on a public release between now and the start of IFComp judging_", they'll see a warning about the comp rules, and the Submit button will be disabled.
- If an author lists their entry's playtime as "_longer than two hours_", they'll see a warning about the judging time limit.

Fix warnings in entry registration form

---

IFComp/root/static/css/ifcomp.css

Some elements are missing CSS rules to make them display correctly in both themes. This pull request notes where rules are missing, and fills in some of them.
More specifically, it:
- Specifies colors for `<select>` and `<option>` in light mode. (This fixes #399.)
- Fixes a typo which prevented the custom `<code>` style from applying, and adds a dark-mode version.
- Makes the navbar (which is always dark) use the dark-mode link color even in light mode.
- Specifies dark-mode colors for some borders and dividers that were falling back on their light-mode colors.
- Specifies `:hover`/`:active` color variations for a few elements that lacked them in dark mode.
- Adds comments documenting where dark-mode colors are still missing. (Filling in these colors should fully fix #394 and #395.)

Document + partially fix missing CSS rules

---

IFComp/root/src/entry/_form.tt

This pull request:
- Adds a checkbox to the entry registration form as specified in #378:
> - [ ]  I hereby grant the Interactive Fiction Technology Foundation (IFComp's organizing body) the non-exclusive right to distribute, without limit, all material I submit to the competition.
- Disables the submit button unless the box is checked.
(It does not currently do anything else, such as display a warning that the box isn't checked or record the fact that the box was checked.)

Add rights grant agreement to registration form (fixes #378)

---

IFComp/root/src/entry/_form.tt

The script that disables the "Submit game information" button until authors agree to terms was also disabling the "Sign out" button. This pull request fixes that.

Fix bug in entry registration form

---

IFComp/root/static/css/ifcomp.css

This pull request:
- Adds a dark mode palette for the `.alert-danger` and `.alert-success` infobox classes (based on existing dark mode colors for `alert-info`), and the `.btn-danger` and `.btn-success` button classes (based on existing dark mode colors for `.btn-primary`)
- Changes the dark-red warning label on form fields with errors to light red in dark mode
- Fixes a few borders I missed last time, as well as a place where buttons were falling back to light-mode colors
This fixes #395, and should fully fix #394 if I haven't missed anything.

Add remaining dark mode colors (fixes #394, #395)

---

IFComp/lib/IFComp/Controller/Admin.pm
IFComp/root/src/admin/index.tt

Adds the link "Download CSV of Results" to /admin. The CSV lists each entry's author and title, place in the overall and Miss Congeniality contests, average score, standard deviation, and total votes cast.
(Like the [ballot CSV](https://github.com/iftechfoundation/ifcomp/pull/409), it doesn't list the column names yet.)

Allow cheez to download a CSV of results

---

IFComp/root/src/entry/list.tt

Fixes #413.
Update Entry becomes inaccessible in phase 6 (`processing_votes`), but /entry still links to it until phase 7 (`over`). This pull request disables the links during phase 6 as well.

Remove 'Update Entry' links after judging ends

---

IFComp/root/lib/site/header
IFComp/root/src/_rating_controls.tt
IFComp/root/src/ballot/index.tt
IFComp/root/src/welcome.tt2

During comp phase 6 (`processing_votes`), rating controls are available but nonfunctional on /ballot. This pull request makes the following changes during phase 6:
- Disables the rating dropdown on /ballot. (Previously it was enabled but threw an error when used.)
- Removes the link to /ballot/vote and the "Add / edit feedback" links from /ballot. (Previously they just led to 403s.)
- Changes header and main page links from "Results" (/comp) to "Entries" (/ballot). (/comp redirects to /ballot during phase 6, since the results aren't ready yet.)

Disable rating controls after voting closes (fixes #412)

---

IFComp/root/src/_current_entry_row.tt
IFComp/root/src/comp/cover_sheet.tt

Entry listings on /ballot and /comp include a bullet after each metadata field. This works as long as the last field (platform) isn't blank:
> _Horror • Half an hour • Web-based_
However, the platform field is left blank if set to "Other", which results in [dangling separators](https://ifcomp.org/ballot#entry-3047):
> _Fantasy • Two hours •_ 
This pull request tweaks the template to print separators only between two non-empty fields.
(A simpler fix would be to just print "Other", but I'm assuming that decision was made for a reason.)

Remove extra • separator before empty game metadata fields

---

IFComp/root/src/comp/cover_sheet.tt

Fixes #423 
In PR #372 we added microdata to the ballot page; here, we're adding microdata to the offline "cover sheet" `games.html` file that gets distributed to the IF Archive.

Add https://schema.org/VideoGame microdata to each cover sheet entry

---

IFComp/root/src/_filter_entries.tt
IFComp/root/src/ballot/index.tt

This adds a filter to hide entries you've already voted on when viewing the ballot, as requested in #431.

Add option to hide already-rated entries from ballot (#431)

---

IFComp/cpanfile
IFComp/script/populate_ifdb_ids.pl

Instead of searching for games by title published during the current calendar year, it'll be more accurate to search IFDB for the current year's competition, then search for games with that competitionid. For each game, we find a link to its IFComp ballot entry, which contains a ballot entry ID.
Fixes #142
I tested this using Docker, but it was kinda thorny, so I'll make a note here of how I did it:
1. I launched IFComp via Docker. I had to `docker compose down && docker compose up --build` to install the XML parser I'm using.
2. In `IFComp-Dev`, I ran `script/change_comp_phase.sh 5` to open the competition for judging.
3. I ran IFDB via Docker on port 8083 (modifying the port in `docker-compose.yml`)
4. I used the [IFComp importer](https://github.com/iftechfoundation/ifdb/tree/main/import …

populate_ifdb_ids: Search IFDB by `competitionid:`, match by entry ID

---

IFComp/lib/IFComp/Controller/Comp.pm
IFComp/t/controller_Comp.t

The main thing IFDB needs this for is to see the the `platform` (+ `is_zcode`) and `ifdb_id` for each entry, which is not visible on `/ballot`, so we can't access it via microdata.
Plus, once the competition is over, it's convenient to know the `place` (and/or `is_disqualified`) for each entry, too.
I did not try to put other data here that is visible via microdata, e.g. author, blurb, etc. partly because that is visible in microdata, but also because some of the information has complex display rules (co-authors, pseudonyms, etc.) The best way to make sure we're using IFComp's latest rules around author display names etc. is to just scrape the microdata off of whatever IFComp is currently displaying, since competition organizers do scrutinize the ballot closely.

Add public JSON of entry IFDB IDs, platform, and place

---

IFComp/root/src/_current_entry_row.tt
IFComp/root/src/_rating_controls.tt
IFComp/root/src/ballot/index.tt
IFComp/t/controller_Ballot.t

We previously added rating controls to /ballot, but had to remove them due to a bug: Firefox's form autocomplete would try to preserve each dropdown's value when the page was refreshed, which caused ratings to appear next to the wrong games when the order was reshuffled.
This pull request fixes that issue by disabling autocomplete on the rating controls. If we want to allow rating from /ballot, it should be possible now.
I've tested briefly in Firefox and Chrome on Windows 10, and everything appears to work as intended.

Fix rating controls on /ballot

---

IFComp/root/src/_current_entry_row.tt
IFComp/root/src/_entry_row.tt
IFComp/root/static/css/ifcomp.css
IFComp/t/lib/IFCompTestData.pm

There's a very long URL in the description for "A few hours later in the day of The Egocentric" in https://ifcomp.org/comp/2024
> Click the question mark on the game's title screen for a walkthrough or use this link: athleticarcade.com/interactivefiction/egocentric2/hints.html
This URL is so long that it causes the page to scroll horizontally on phones.
In this commit, we're adding [`overflow-wrap: anywhere`](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap#anywhere) to the blurb.

Allow long URLs in blurb to wrap

---

IFComp/root/src/_current_entry_row.tt
IFComp/root/src/_entry_row.tt
IFComp/root/static/css/ifcomp.css

#446 did part of the job, but it's still scrolling horizontally on an URL, this time in the "Cover art by" section.

Wrap long cover artist

---

IFComp/root/src/comp/index.tt

Mobile buttons layout

---

IFComp-Dev/docker-app/Dockerfile

I wanted to upgrade to a newer version of Perl, but when I tried upgrading to the latest stable version 5.42, `DBD::mysql` failed to install. 5.34 worked, so, here we are.
Fixes #454

Upgrade dev environment to Perl 5.34
