iftechfoundation/ifcomp

- IFComp/lib/IFComp/Controller/Ballot.pm
- IFComp/lib/IFComp/Schema/Result/Entry.pm
- IFComp/root/src/ballot/index.tt
- IFComp/root/src/ballot/vote.tt
This required changing the ballot controller/templates so it was looping over a list instead of a ResultSet, but that seems like it'll be fine in practice performance-wise.
> Issue 60: Add sort_title attribute and use it to sort entries instead of raw title

- .gitignore
- IFComp/entries/.gitignore
- IFComp/lib/IFComp/Controller/Admin.pm
- IFComp/lib/IFComp/Controller/Admin/Voting.pm
- IFComp/lib/IFComp/Controller/Admin/Voting/IP.pm
- IFComp/lib/IFComp/Controller/Admin/Voting/User.pm
- IFComp/lib/IFComp/Controller/Ballots.pm
- IFComp/lib/IFComp/Schema/Result/Comp.pm
- IFComp/lib/IFComp/Schema/Result/Entry.pm
- IFComp/lib/IFComp/Schema/Result/User.pm
- IFComp/lib/IFComp/Schema/Result/Vote.pm
- IFComp/lib/IFComp/Schema/ResultSet/Comp.pm
- IFComp/lib/IFComp/Schema/ResultSet/Entry.pm
- IFComp/root/lib/site/header
- IFComp/root/lib/site/html
- IFComp/root/src/about/donate.tt
- IFComp/root/src/admin/index.tt
- IFComp/root/src/admin/voting/index.tt
- IFComp/root/src/admin/voting/show_entry.tt
- IFComp/root/src/admin/voting/show_ip.tt
- IFComp/root/src/admin/voting/show_user.tt
- IFComp/root/static/css/ifcomp.css
- IFComp/root/static/downloads/.gitignore
Ballot report:
- New Admin section (needs to be secured and linked to the main app somehow)
- New Voting section that contains the Ballot Reports
- Ballot activity shown for Entries, Users and IP
> Ballot report

- IFComp/root/src/about/if.tt
I was reading through the "About IF" page and ran across a bad link for Blue Lacuna. I've updated it to what I think should be the correct URL.
> Update link to Blue Lacuna.

- IFComp/root/src/_current_entry_row.tt
> Changing ballot buttons into links

- IFComp/lib/IFComp/Controller/Entry.pm
- IFComp/lib/IFComp/Controller/Play.pm
- IFComp/lib/IFComp/Controller/Root.pm
- IFComp/root/src/error_404.tt
Fixes #90.
Feel free to edit the content of the template if you have better wording to use.
> Add 404 page

- IFComp/cpanfile
- IFComp/lib/IFComp/Schema.pm
- IFComp/lib/IFComp/Schema/Result/AuthToken.pm
- IFComp/lib/IFComp/Schema/Result/Comp.pm
- IFComp/lib/IFComp/Schema/Result/Entry.pm
- IFComp/lib/IFComp/Schema/Result/EntryUpdate.pm
- IFComp/lib/IFComp/Schema/Result/FederatedSite.pm
- IFComp/lib/IFComp/Schema/Result/Prize.pm
- IFComp/lib/IFComp/Schema/Result/Role.pm
- IFComp/lib/IFComp/Schema/Result/Session.pm
- IFComp/lib/IFComp/Schema/Result/Transcript.pm
- IFComp/lib/IFComp/Schema/Result/User.pm
- IFComp/lib/IFComp/Schema/Result/UserRole.pm
- IFComp/lib/IFComp/Schema/Result/Vote.pm
- IFComp/script/README.md
- IFComp/script/ifcomp_dump_schema.pl
- README.md
Addresses #92.
This is built on top of #103, since that adds the ifcomp_dump_schema script.
> Add readme for scripts

- IFComp/lib/IFComp/Schema/Result/Entry.pm
- IFComp/root/src/entry/list.tt
- IFComp/t/entry_processing.t
This extends transcription visibility to quixe games.
It also removes the restriction of displaying transcript links only during the judging period. In this way, authors can test their own games' transcription powers prior to judging, and why not?
(And, yes, I was wrong earlier about having no further additions to the quixe branch before throwing it to testers!)
> This extends transcription visibility to quixe games.

- IFComp/root/src/_current_entry_row.tt
Also, remove spurious italcization from the "format" field display.
> Display the new "genre" field, if defined.

- IFComp/lib/IFComp.pm
- IFComp/lib/IFComp/Controller/Admin.pm
- IFComp/lib/IFComp/Controller/Ballot.pm
- IFComp/lib/IFComp/Controller/Root.pm
- IFComp/root/src/error_403.tt
- IFComp/t/admin.t
- IFComp/t/auth.t
- IFComp/t/controller_Ballot.t
- IFComp/t/feedback.t
- IFComp/t/lib/IFCompTest.pm
> Add a 'forbidden' page - fixes #91

- .travis.yml
> Bump perl from 5.20.2 to 5.30.2 in Travis-CI config

- IFComp/root/src/about/file_formats.tt
Also modified the [Interpreter](http://www.ifwiki.org/index.php/Interpreter) page at ifwiki to point players at Lectrote based on input from the discussion page over at intfiction.org
> Update file format page. Fixes #199

- IFComp/root/src/about/prizes.tt
Adding language about Steam keys.
> Specify that steam keys are not acceptable prizes (except when they are)

- IFComp/root/src/comp/index.tt
I couldn't really test this on my dev environment with anemic data (one hand-inserted comp, one hand-inserted entry, with no votes); the highchart didn't even render. But I was able to verify that the highchart code was still being called, and so I think it's worth having somebody with real DB access test this.
> Yield the main thread between each chart. Fixes #203

- IFComp/lib/IFComp/Controller/Entry.pm
- IFComp/lib/IFComp/Controller/Play.pm
I think this will help address #161 (for the current comp, not past comps). Untested. I don't really know what I'm doing 😨. Ideally it would also set Last-Modified or an ETag, but I don't know how to do that. This will still make a big difference though. If it works!
> Cache cover images for a day

- IFComp/ifcomp.psgi
- IFComp/lib/Plack/Middleware/IFComp.pm
> Making certain internal paths to resource and config directories relative.

- IFComp/script/run_test.sh
Added some missing documentation, and removed the erroneous update of tidyall. The tidyall version is specified in the cpanfile and we'll update that periodically as separate PRs.
> update convenience script for running tests

- IFComp/root/src/ballot/index.tt
- IFComp/root/src/ballot/vote.tt
> Less jQuery

- IFComp/lib/IFComp/Form/Entry.pm
- IFComp/t/platform_test_entries/116/main/my_game.html
Set the field maxwidth to 250 & validate input on the backend too.
> Limit cw field to 250, fixes #301

- IFComp/lib/IFComp/Schema/Result/Entry.pm
> Make the transcript recording insertion code safe in the event that something weird was uploaded

- IFComp/lib/IFComp/Controller/Entry.pm
- IFComp/lib/IFComp/Schema/Result/User.pm
- IFComp/mail/author_reminder/body.tt
- IFComp/mail/author_reminder/manifest.json
Refreshing PR with a new branch because the old one got really messy. Hi, I'm bad with git.
> Send author reminder email, fixes #320

- IFComp-Dev/docker-app/docker-script/change_comp_phase.pl
- IFComp-Dev/script/change_comp_phase.sh
Adds a script for setting the comp phase. There is room for improvement, but this has been working well for me.
> Add script for setting comp phase.

- IFComp/lib/IFComp/Schema/Result/Entry.pm
- IFComp/root/src/_current_entry_row.tt
- IFComp/t/entry_processing.t
The biggest part of #248, thanks Adam!
> Create a parchment page for TADS games

- IFComp/root/src/_filter_entries.tt
- IFComp/root/src/ballot/index.tt
- IFComp/root/static/css/ifcomp.css
While this does not implement the full sorting and filtering that we eventually would like to have, it's a step in the right direction.
> Allow Judges to filter games based on simple criteria

- IFComp/root/src/_filter_entries.tt
- IFComp/root/src/ballot/index.tt
Only show the platforms in the filter choices which have games in the comp
> Filter filters, fixes #342

- IFComp/lib/IFComp/Form/Entry.pm
- IFComp/lib/IFComp/Schema/Result/Entry.pm
- IFComp/root/src/_current_entry_row.tt
- IFComp/root/src/_entry_row.tt
- IFComp/root/src/entry/_form.tt
cover credit capability
Table modification:
`alter table entry add column cover_artist char(128) after author_pseudonym`
> Allow authors to credit the cover artist(s)

- IFComp/root/lib/site/html
I didn't realise the path needs to be set too.
> parchment_theme cookie needs to set path=/ as well

- IFComp/root/src/_current_entry_row.tt
- IFComp/root/src/_entry_title.tt
- IFComp/root/src/author_name.tt
- IFComp/root/src/ballot/index.tt
- IFComp/root/src/coauthor_name.tt
This will make it substantially easier to screen-scrape the ballot, so we can automatically submit IFDB entries based on it.
> Add https://schema.org/VideoGame microdata to each ballot entry

- CONTRIBUTING.md
- IFComp/mail/validate_registration/body.tt
- IFComp/root/src/about/contact.tt
- IFComp/root/src/user/register.tt
- IFComp/root/src/welcome.tt2
Updates CONTRIBUTING.md with the correct port number (13000) and branch names (`main`/`develop`), and fixes a handful of typos across the site.
> Minor text corrections

- IFComp/root/src/entry/_form.tt
1. Removed the superfluous `[% INCLUDE scripts %]` from `_form.tt`.
2. Updated the content warning guidelines as requested.
> Registration form tweaks

- IFComp/root/src/error_404.tt
- IFComp/root/static/css/ifcomp.css
This pull request:
- Fixes a typo in the 404 page
- Slightly lightens the color of two `.label` elements which were difficult to read on dark mode
> Minor text and style edits

- IFComp/lib/IFComp/Controller/Admin.pm
results.csv now only counts games that haven't been disqualified.
> Exclude disqualified entries from results CSV

- IFComp/t/lib/IFCompTestData.pm
I had to ask @mjmusante to tell me the password. It's just a test password, so it should be safe to commit, in place of the magic number that was there before.
> Commit the password for the test data users

- IFComp/root/src/_current_entry_row.tt
> Add a little space between the Vote icon and the word Vote

- IFComp/root/src/_current_entry_row.tt
- IFComp/root/src/about/faq.tt
- IFComp/root/src/about/how_to_enter.tt
- IFComp/root/src/comp/cover_sheet.tt
- IFComp/root/src/entry/_form.tt
- IFComp/root/src/entry/preview.tt
Fixes:
1. An oversight in #420, where the interaction style field was treated as non-empty even if set to 'Other' (which isn't displayed on the entry listing).
2. A few typos.
> Text and formatting fixes

- IFComp/root/static/css/ifcomp.css
> Add a border on `<select multiple>` elements

- IFComp/root/static/css/ifcomp.css
> Add a scroll margin to ballot entries

- IFComp/root/src/_current_entry_row.tt
- IFComp/root/src/_rating_controls.tt
- IFComp/root/src/ballot/index.tt
- IFComp/t/controller_Ballot.t
> Fix rating controls on /ballot (#441)
